CC=g++
CFLAGS=-Wall -pedantic -g
INCLUDE=-I./include

linked_list_test: linked_list_test.cpp
	$(CC) $(CFLAGS) $(INCLUDE) -o linked_list_test linked_list_test.cpp

.PHONY:clean
clean:
	rm -f *.o linked_list_test 