CC=g++
CFLAGS=-Wall -pedantic -g
INCLUDE=-I./include

unionfind_test: unionfind_test.cpp
	$(CC) $(CFLAGS) $(INCLUDE) -o unionfind_test unionfind_test.cpp

.PHONY:clean
clean:
	rm -f *.o unionfind_test 